[package]

name = "api-versioning-experiment"
version = "0.1.0"
authors = ["Jacob MacDonald <jaccarmac@gmail.com>"]

[dependencies]

rocket = "*"
rocket_codegen = "*"
rocket_contrib = "*"
serde = "*"
serde_derive = "*"
